/*
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.payone.commerce.platform.lib.models;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * Object containing information about the end customer&#39;s bank account.
 */
@JsonPropertyOrder({
    BankAccountInformation.JSON_PROPERTY_IBAN,
    BankAccountInformation.JSON_PROPERTY_ACCOUNT_HOLDER
})
public class BankAccountInformation implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_IBAN = "iban";
  private String iban;

  public static final String JSON_PROPERTY_ACCOUNT_HOLDER = "accountHolder";
  private String accountHolder;

  public BankAccountInformation() {
  }

  public BankAccountInformation iban(String iban) {

    this.iban = iban;
    return this;
  }

  /**
   * IBAN of the end customer&#39;s bank account. The IBAN is the International
   * Bank Account Number. It is an internationally agreed format for the BBAN and
   * includes the ISO country code and two check digits.
   * 
   * @return iban
   **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IBAN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getIban() {
    return iban;
  }

  @JsonProperty(JSON_PROPERTY_IBAN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIban(String iban) {
    this.iban = iban;
  }

  public BankAccountInformation accountHolder(String accountHolder) {

    this.accountHolder = accountHolder;
    return this;
  }

  /**
   * Account holder of the bank account with the given IBAN. Does not necessarily
   * have to be the end customer (e.g. joint accounts).
   * 
   * @return accountHolder
   **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ACCOUNT_HOLDER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAccountHolder() {
    return accountHolder;
  }

  @JsonProperty(JSON_PROPERTY_ACCOUNT_HOLDER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccountHolder(String accountHolder) {
    this.accountHolder = accountHolder;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BankAccountInformation bankAccountInformation = (BankAccountInformation) o;
    return Objects.equals(this.iban, bankAccountInformation.iban) &&
        Objects.equals(this.accountHolder, bankAccountInformation.accountHolder);
  }

  @Override
  public int hashCode() {
    return Objects.hash(iban, accountHolder);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BankAccountInformation {\n");
    sb.append("    iban: ").append(toIndentedString(iban)).append("\n");
    sb.append("    accountHolder: ").append(toIndentedString(accountHolder)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `iban` to the URL query string
    if (getIban() != null) {
      try {
        joiner.add(String.format("%siban%s=%s", prefix, suffix,
            URLEncoder.encode(String.valueOf(getIban()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `accountHolder` to the URL query string
    if (getAccountHolder() != null) {
      try {
        joiner.add(String.format("%saccountHolder%s=%s", prefix, suffix,
            URLEncoder.encode(String.valueOf(getAccountHolder()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}
