/*
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.payone.commerce.platform.lib.models;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * CapturePaymentResponse
 */
@JsonPropertyOrder({
    CapturePaymentResponse.JSON_PROPERTY_CAPTURE_OUTPUT,
    CapturePaymentResponse.JSON_PROPERTY_STATUS,
    CapturePaymentResponse.JSON_PROPERTY_STATUS_OUTPUT,
    CapturePaymentResponse.JSON_PROPERTY_ID
})
public class CapturePaymentResponse implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_CAPTURE_OUTPUT = "captureOutput";
  private CaptureOutput captureOutput;

  public static final String JSON_PROPERTY_STATUS = "status";
  private StatusValue status;

  public static final String JSON_PROPERTY_STATUS_OUTPUT = "statusOutput";
  private PaymentStatusOutput statusOutput;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public CapturePaymentResponse() {
  }

  public CapturePaymentResponse captureOutput(CaptureOutput captureOutput) {

    this.captureOutput = captureOutput;
    return this;
  }

  /**
   * Get captureOutput
   * 
   * @return captureOutput
   **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CAPTURE_OUTPUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CaptureOutput getCaptureOutput() {
    return captureOutput;
  }

  @JsonProperty(JSON_PROPERTY_CAPTURE_OUTPUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCaptureOutput(CaptureOutput captureOutput) {
    this.captureOutput = captureOutput;
  }

  public CapturePaymentResponse status(StatusValue status) {

    this.status = status;
    return this;
  }

  /**
   * Get status
   * 
   * @return status
   **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatusValue getStatus() {
    return status;
  }

  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(StatusValue status) {
    this.status = status;
  }

  public CapturePaymentResponse statusOutput(PaymentStatusOutput statusOutput) {

    this.statusOutput = statusOutput;
    return this;
  }

  /**
   * Get statusOutput
   * 
   * @return statusOutput
   **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS_OUTPUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PaymentStatusOutput getStatusOutput() {
    return statusOutput;
  }

  @JsonProperty(JSON_PROPERTY_STATUS_OUTPUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatusOutput(PaymentStatusOutput statusOutput) {
    this.statusOutput = statusOutput;
  }

  public CapturePaymentResponse id(String id) {

    this.id = id;
    return this;
  }

  /**
   * Unique payment transaction identifier of the payment gateway.
   * 
   * @return id
   **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }

  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CapturePaymentResponse capturePaymentResponse = (CapturePaymentResponse) o;
    return Objects.equals(this.captureOutput, capturePaymentResponse.captureOutput) &&
        Objects.equals(this.status, capturePaymentResponse.status) &&
        Objects.equals(this.statusOutput, capturePaymentResponse.statusOutput) &&
        Objects.equals(this.id, capturePaymentResponse.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(captureOutput, status, statusOutput, id);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CapturePaymentResponse {\n");
    sb.append("    captureOutput: ").append(toIndentedString(captureOutput)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    statusOutput: ").append(toIndentedString(statusOutput)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `captureOutput` to the URL query string
    if (getCaptureOutput() != null) {
      joiner.add(getCaptureOutput().toUrlQueryString(prefix + "captureOutput" + suffix));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      try {
        joiner.add(String.format("%sstatus%s=%s", prefix, suffix,
            URLEncoder.encode(String.valueOf(getStatus()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `statusOutput` to the URL query string
    if (getStatusOutput() != null) {
      joiner.add(getStatusOutput().toUrlQueryString(prefix + "statusOutput" + suffix));
    }

    // add `id` to the URL query string
    if (getId() != null) {
      try {
        joiner.add(String.format("%sid%s=%s", prefix, suffix,
            URLEncoder.encode(String.valueOf(getId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}
