/*
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.payone.commerce.platform.lib.models;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;

import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * Object containing the specific input details for payments that involve
 * redirects to 3rd parties to complete, like iDeal and PayPal
 */
@JsonPropertyOrder({
    RedirectPaymentMethodSpecificInput.JSON_PROPERTY_REQUIRES_APPROVAL,
    RedirectPaymentMethodSpecificInput.JSON_PROPERTY_PAYMENT_PROCESSING_TOKEN,
    RedirectPaymentMethodSpecificInput.JSON_PROPERTY_REPORTING_TOKEN,
    RedirectPaymentMethodSpecificInput.JSON_PROPERTY_TOKENIZE,
    RedirectPaymentMethodSpecificInput.JSON_PROPERTY_PAYMENT_PRODUCT_ID,
    RedirectPaymentMethodSpecificInput.JSON_PROPERTY_PAYMENT_PRODUCT840_SPECIFIC_INPUT,
    RedirectPaymentMethodSpecificInput.JSON_PROPERTY_REDIRECTION_DATA
})
public class RedirectPaymentMethodSpecificInput implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_REQUIRES_APPROVAL = "requiresApproval";
  private Boolean requiresApproval;

  public static final String JSON_PROPERTY_PAYMENT_PROCESSING_TOKEN = "paymentProcessingToken";
  private String paymentProcessingToken;

  public static final String JSON_PROPERTY_REPORTING_TOKEN = "reportingToken";
  private String reportingToken;

  public static final String JSON_PROPERTY_TOKENIZE = "tokenize";
  private Boolean tokenize;

  public static final String JSON_PROPERTY_PAYMENT_PRODUCT_ID = "paymentProductId";
  private Integer paymentProductId;

  public static final String JSON_PROPERTY_PAYMENT_PRODUCT840_SPECIFIC_INPUT = "paymentProduct840SpecificInput";
  private RedirectPaymentProduct840SpecificInput paymentProduct840SpecificInput;

  public static final String JSON_PROPERTY_REDIRECTION_DATA = "redirectionData";
  private RedirectionData redirectionData;

  public RedirectPaymentMethodSpecificInput() {
  }

  @JsonCreator
  public RedirectPaymentMethodSpecificInput(
      @JsonProperty(JSON_PROPERTY_REPORTING_TOKEN) String reportingToken) {
    this();
    this.reportingToken = reportingToken;
  }

  public RedirectPaymentMethodSpecificInput requiresApproval(Boolean requiresApproval) {

    this.requiresApproval = requiresApproval;
    return this;
  }

  /**
   * * true &#x3D; the payment requires approval before the funds will be captured
   * using the Approve payment or Capture payment API * false &#x3D; the payment
   * does not require approval, and the funds will be captured automatically If
   * the parameter is not provided in the request, the default value will be true
   * 
   * @return requiresApproval
   **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REQUIRES_APPROVAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getRequiresApproval() {
    return requiresApproval;
  }

  @JsonProperty(JSON_PROPERTY_REQUIRES_APPROVAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequiresApproval(Boolean requiresApproval) {
    this.requiresApproval = requiresApproval;
  }

  public RedirectPaymentMethodSpecificInput paymentProcessingToken(String paymentProcessingToken) {

    this.paymentProcessingToken = paymentProcessingToken;
    return this;
  }

  /**
   * ID of the token to use to create the payment.
   * 
   * @return paymentProcessingToken
   **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYMENT_PROCESSING_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPaymentProcessingToken() {
    return paymentProcessingToken;
  }

  @JsonProperty(JSON_PROPERTY_PAYMENT_PROCESSING_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentProcessingToken(String paymentProcessingToken) {
    this.paymentProcessingToken = paymentProcessingToken;
  }

  /**
   * Token to identify the card in the reporting.
   * 
   * @return reportingToken
   **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPORTING_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReportingToken() {
    return reportingToken;
  }

  public RedirectPaymentMethodSpecificInput tokenize(Boolean tokenize) {

    this.tokenize = tokenize;
    return this;
  }

  /**
   * Indicates if this transaction should be tokenized * true - Tokenize the
   * transaction. * false - Do not tokenize the transaction, unless it would be
   * tokenized by other means such as auto- tokenization of recurring payments.
   * example: false
   * 
   * @return tokenize
   **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOKENIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTokenize() {
    return tokenize;
  }

  @JsonProperty(JSON_PROPERTY_TOKENIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTokenize(Boolean tokenize) {
    this.tokenize = tokenize;
  }

  public RedirectPaymentMethodSpecificInput paymentProductId(Integer paymentProductId) {

    this.paymentProductId = paymentProductId;
    return this;
  }

  /**
   * Payment product identifier - please check product documentation for a full
   * overview of possible values.
   * minimum: 0
   * maximum: 99999
   * 
   * @return paymentProductId
   **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYMENT_PRODUCT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPaymentProductId() {
    return paymentProductId;
  }

  @JsonProperty(JSON_PROPERTY_PAYMENT_PRODUCT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentProductId(Integer paymentProductId) {
    this.paymentProductId = paymentProductId;
  }

  public RedirectPaymentMethodSpecificInput paymentProduct840SpecificInput(
      RedirectPaymentProduct840SpecificInput paymentProduct840SpecificInput) {

    this.paymentProduct840SpecificInput = paymentProduct840SpecificInput;
    return this;
  }

  /**
   * Get paymentProduct840SpecificInput
   * 
   * @return paymentProduct840SpecificInput
   **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYMENT_PRODUCT840_SPECIFIC_INPUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RedirectPaymentProduct840SpecificInput getPaymentProduct840SpecificInput() {
    return paymentProduct840SpecificInput;
  }

  @JsonProperty(JSON_PROPERTY_PAYMENT_PRODUCT840_SPECIFIC_INPUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentProduct840SpecificInput(RedirectPaymentProduct840SpecificInput paymentProduct840SpecificInput) {
    this.paymentProduct840SpecificInput = paymentProduct840SpecificInput;
  }

  public RedirectPaymentMethodSpecificInput redirectionData(RedirectionData redirectionData) {

    this.redirectionData = redirectionData;
    return this;
  }

  /**
   * Get redirectionData
   * 
   * @return redirectionData
   **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REDIRECTION_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RedirectionData getRedirectionData() {
    return redirectionData;
  }

  @JsonProperty(JSON_PROPERTY_REDIRECTION_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRedirectionData(RedirectionData redirectionData) {
    this.redirectionData = redirectionData;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RedirectPaymentMethodSpecificInput redirectPaymentMethodSpecificInput = (RedirectPaymentMethodSpecificInput) o;
    return Objects.equals(this.requiresApproval, redirectPaymentMethodSpecificInput.requiresApproval) &&
        Objects.equals(this.paymentProcessingToken, redirectPaymentMethodSpecificInput.paymentProcessingToken) &&
        Objects.equals(this.reportingToken, redirectPaymentMethodSpecificInput.reportingToken) &&
        Objects.equals(this.tokenize, redirectPaymentMethodSpecificInput.tokenize) &&
        Objects.equals(this.paymentProductId, redirectPaymentMethodSpecificInput.paymentProductId) &&
        Objects.equals(this.paymentProduct840SpecificInput,
            redirectPaymentMethodSpecificInput.paymentProduct840SpecificInput)
        &&
        Objects.equals(this.redirectionData, redirectPaymentMethodSpecificInput.redirectionData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requiresApproval, paymentProcessingToken, reportingToken, tokenize, paymentProductId,
        paymentProduct840SpecificInput, redirectionData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RedirectPaymentMethodSpecificInput {\n");
    sb.append("    requiresApproval: ").append(toIndentedString(requiresApproval)).append("\n");
    sb.append("    paymentProcessingToken: ").append(toIndentedString(paymentProcessingToken)).append("\n");
    sb.append("    reportingToken: ").append(toIndentedString(reportingToken)).append("\n");
    sb.append("    tokenize: ").append(toIndentedString(tokenize)).append("\n");
    sb.append("    paymentProductId: ").append(toIndentedString(paymentProductId)).append("\n");
    sb.append("    paymentProduct840SpecificInput: ").append(toIndentedString(paymentProduct840SpecificInput))
        .append("\n");
    sb.append("    redirectionData: ").append(toIndentedString(redirectionData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `requiresApproval` to the URL query string
    if (getRequiresApproval() != null) {
      try {
        joiner.add(String.format("%srequiresApproval%s=%s", prefix, suffix,
            URLEncoder.encode(String.valueOf(getRequiresApproval()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `paymentProcessingToken` to the URL query string
    if (getPaymentProcessingToken() != null) {
      try {
        joiner.add(String.format("%spaymentProcessingToken%s=%s", prefix, suffix,
            URLEncoder.encode(String.valueOf(getPaymentProcessingToken()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `reportingToken` to the URL query string
    if (getReportingToken() != null) {
      try {
        joiner.add(String.format("%sreportingToken%s=%s", prefix, suffix,
            URLEncoder.encode(String.valueOf(getReportingToken()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `tokenize` to the URL query string
    if (getTokenize() != null) {
      try {
        joiner.add(String.format("%stokenize%s=%s", prefix, suffix,
            URLEncoder.encode(String.valueOf(getTokenize()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `paymentProductId` to the URL query string
    if (getPaymentProductId() != null) {
      try {
        joiner.add(String.format("%spaymentProductId%s=%s", prefix, suffix,
            URLEncoder.encode(String.valueOf(getPaymentProductId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `paymentProduct840SpecificInput` to the URL query string
    if (getPaymentProduct840SpecificInput() != null) {
      joiner.add(
          getPaymentProduct840SpecificInput().toUrlQueryString(prefix + "paymentProduct840SpecificInput" + suffix));
    }

    // add `redirectionData` to the URL query string
    if (getRedirectionData() != null) {
      joiner.add(getRedirectionData().toUrlQueryString(prefix + "redirectionData" + suffix));
    }

    return joiner.toString();
  }

}
