/*
 * This source file was generated by the Gradle 'init' task
 */
package com.payone.commerce.platform.lib.endpoints;

import com.payone.commerce.platform.lib.models.CreateCommerceCaseRequest;

public class CommerceCaseApiClient {

    String apiKey;

    public CommerceCaseApiClient(String apiKey) {
        this.apiKey = apiKey;
    }

    public String createCommerceCaseRequest(String merchantId, CreateCommerceCaseRequest payload) {
        return "Hello, World!";
    }
}
