/*
 * This source file was generated by the Gradle 'init' task
 */
package com.payone.commerce.platform.lib;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class TestTest {
    @Test
    void test() {

        assertEquals(0, 0);
    }

}
