/*
 * Commerce Platform API
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments. 
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.payone.commerce.platform.models;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.StringJoiner;

/**
 * Object containing specififc information for PAYONE Secured Installments.
 */
@JsonPropertyOrder({
  PaymentProduct3391SpecificOutput.JSON_PROPERTY_INSTALLMENT_OPTIONS
})
public class PaymentProduct3391SpecificOutput implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_INSTALLMENT_OPTIONS = "installmentOptions";
  private List<InstallmentOption> installmentOptions;

  public PaymentProduct3391SpecificOutput() {
  }

  public PaymentProduct3391SpecificOutput installmentOptions(List<InstallmentOption> installmentOptions) {
    
    this.installmentOptions = installmentOptions;
    return this;
  }

  public PaymentProduct3391SpecificOutput addInstallmentOptionsItem(InstallmentOption installmentOptionsItem) {
    if (this.installmentOptions == null) {
      this.installmentOptions = new ArrayList<>();
    }
    this.installmentOptions.add(installmentOptionsItem);
    return this;
  }

   /**
   * List of installment options.
   * @return installmentOptions
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INSTALLMENT_OPTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<InstallmentOption> getInstallmentOptions() {
    return installmentOptions;
  }


  @JsonProperty(JSON_PROPERTY_INSTALLMENT_OPTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInstallmentOptions(List<InstallmentOption> installmentOptions) {
    this.installmentOptions = installmentOptions;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentProduct3391SpecificOutput paymentProduct3391SpecificOutput = (PaymentProduct3391SpecificOutput) o;
    return Objects.equals(this.installmentOptions, paymentProduct3391SpecificOutput.installmentOptions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(installmentOptions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentProduct3391SpecificOutput {\n");
    sb.append("    installmentOptions: ").append(toIndentedString(installmentOptions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `installmentOptions` to the URL query string
    if (getInstallmentOptions() != null) {
      for (int i = 0; i < getInstallmentOptions().size(); i++) {
        if (getInstallmentOptions().get(i) != null) {
          joiner.add(getInstallmentOptions().get(i).toUrlQueryString(String.format("%sinstallmentOptions%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }

}

