/*
 * This source file was generated by the Gradle 'init' task
 */
package com.payone.commerce.platform.app;

import com.payone.commerce.platform.lib.endpoints.CommerceCaseApiClient;
import com.payone.commerce.platform.lib.models.CreateCommerceCaseRequest;

public class App {
    public static void main(String[] args) {
        CommerceCaseApiClient client = new CommerceCaseApiClient("some_key");
        CreateCommerceCaseRequest payload = new CreateCommerceCaseRequest();
        payload.setMerchantReference("1234");
        String res = client.createCommerceCaseRequest("merchant_id", payload);

        System.out.println(res);
    }
}
