/*
 * This source file was generated by the Gradle 'init' task
 */
package com.payone.commerce.platform.app;

import com.payone.commerce.platform.lib.CommunicatorConfiguration;
import com.payone.commerce.platform.lib.endpoints.CommerceCaseApiClient;

public class App {
    public static void main(String[] args) {

        String API_KEY = System.getenv("API_KEY");
        String API_SECRET = System.getenv("API_SECRET");

        CommunicatorConfiguration config = new CommunicatorConfiguration(API_KEY, API_SECRET);

        CommerceCaseApiClient client = new CommerceCaseApiClient(config);

        // CreateCommerceCaseRequest payload = new CreateCommerceCaseRequest();
        // payload.setMerchantReference("123456");

        // String res = client.createCommerceCaseRequest("P1_18352_2013244", payload);

        String res = client.getAllCommerceCaseRequest("P1_18352_2013244");

        System.out.println(res);
    }
}
