/*
 * This source file was generated by the Gradle 'init' task
 */
package com.payone.commerce.platform.app;

import com.payone.commerce.platform.lib.Test;

public class App {
    public static void main(String[] args) {
        System.out.println(Test.test());
    }
}
